# Linear Algebra

You need to know a little bit of linear algebra because a number of the machine learning techniques are expressed more compactly if you use the appropriate notation.

We shall see some applications later, but remember that it is all about having a shorthand that allows us to express complex formulas.

## numpy
Just as we have a mathematical shorthand, python has a module called that implements these operations.  (While there are other things in numpy, the focus of this notebook will be on the operations with vectors and matrices.)  

The numpy library is written C, so it is fast, fast, fast. If you are going to be using arrays for a computation task in python this is what you should use. We will explore numpy a little bit and implement a few things ourselves, but mostly we will be using other packages that use numpy for their underlying operations.


# Vectors
For example, if you have a list of values, we can use a vector $v=[0, 1, 3, 4]$.

In general, we would write $x = [x_1, x_2, ..., x_n]$ and can refer to a particular value with the subscript notation $x_i$ is the i'th value in the vector.

## Vector addition
If we have two vectors, we can combine them by adding their components in a pairwise fashion and write it using the + symbol.

$x + y = [x_1+y_1, x_2+y_2, ..., x_n+y_n]$

Lets look at some code that does this using python lists.


In [2]:
x = [1, 2, 3, 4]
y = [4, 6, 10, 15]

# adding two lists is append, clearly not what we want
print(x+y)

result = []
for index in range(len(x)) :
    result.append(x[index] + y[index])
print(result)

[1, 2, 3, 4, 4, 6, 10, 15]
[5, 8, 13, 19]


  
## How can I use numpy to add vectors?
You need to import the package. In the olden days, the package name was np, so we are going to use that name when we work with numpy


In [3]:
import numpy as np

### Numpy Vectors
Numpy has its own data type for vectors and arrays called `numpy.array`.  While it may look like a list, it is completely different.

To create a numpy vector we need to give it a list that contains the values in our vector.

In [4]:
#This vector has 3 values in it
vector1 = np.array([1, 2, 3])
print(vector1)

#This vector has 4 values in it
vector2 = np.array([1.5, 2.7, 8.9, 24])
print(vector2)

[1 2 3]
[ 1.5  2.7  8.9 24. ]


### Numpy Vector addition
No looping is needed, we just do an add on the two vectors and the result appears!

In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 6, 10, 15])

# adding two vectors gives us a new vector
print(x+y)

[ 5  8 13 19]


## Vector product
If we have two vectors, we can combine them by doing a multiplication.  There are three ways that we can do a multiplication depending on the type of the result. 

1. Pairwise multiplication of corresponding values results in a vector. Surprisingly, this is not usually what we mean.
2. The inner product multiplies the corresponding values and then adds each of the values resulting in a scalar (single) value. This is also called a dot product and is usually what is meant by multiplication.
3. The outer product results in a matrix.

The dot product is:

$x \bullet y = x_1  y_1 + x_2 y_2 + ...+ x_ny_n$

Lets look at some code that does this using python lists.

In [6]:
x = [1, 2, 3, 4]
y = [4, 6, 10, 15]

# The result is a single value
result = 0
for index in range(len(x)) :
    result += (x[index] * y[index])
print(result)

106


and here is the numpy equivalent

In [12]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 6, 10, 15])

# Here is the dot product
print(x.dot(y))

# Quick aside, If you wanted to do the pairwise operation, it uses *
print(x*y)

106
[ 4 12 30 60]


## How long is my vector?
One way of thinking about a vector is that it is a directed line segment.  So for example, the vector (1, -2, 3) is goes 1 unit in the positive x direction, 2 units in the negative y direction, and 3 units in the positive z direction.  To find the length, we generalize the Pythagoean theorem where $x^2 + y^2 = s^2$


![Pythagorean Theorem](imgs/pythagorean.gif)



In general the norm (length) of a vector $x$ is given by the formula $ |x|^2 = x_1  x_1 + x_2 x_2 + ...+ x_nx_n$.

Conveniently, the right hand side is the dot product of $x$ with itself.

Lets look at the numpy version.

In [7]:
x = np.array([1, -2, 3])

from math import sqrt
# Here is the dot product
print(sqrt(x.dot(x)))

# Or we can compute the norm directly using the predefined method
print(np.linalg.norm(x))

3.7416573867739413
3.7416573867739413


# Matrices
A 2D matrix is a rectangular arrangement of values.  There are a number of ways that matrices can be used, but the basics involve combining two matrices or a matrix with a vector.

Here is an example of a 4 by 3 matrix $\mathbf{M} = \left[\begin{array}{ccc}1&2&3\\
4&5&6\\
7&8&9\\
10&11&12
\end{array}
\right]$

We can refer to individual values in the matrix via subscripts like so:

$\mathbf{A} = \left[\begin{array}{cccc}
a_{1,1}&a_{1,2}&...&a_{1,n}\\
a_{2,1}&a_{2,2}&...&a_{2,n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m,1}&a_{m,2}&...&a_{m,n}
\end{array}
\right]$

where A is m rows by n columns. 

We will not talk about them, but our matrices can have arbitrary numbers of subscripts.  A 3D array would have 3 subscripts for example.


# Combining a Matrix and a Vector
One standard operation is to multiply a matrix with a vector resulting in a new vector. This kind of operation is often linked with transformation of data.  Matrices used in this fashion are called _Transformation Matrices_.  We will define how to do the operation here and look at the corresponding python code and then show that it can be done faster with numpy.

$\mathbf{A}x = \left[\begin{array}{cccc}
a_{1,1}&a_{1,2}&...&a_{1,n}\\
a_{2,1}&a_{2,2}&...&a_{2,n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m,1}&a_{m,2}&...&a_{m,n}
\end{array} 
\right]
\left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\vdots\\
x_n
\end{array} 
\right]
= 
\left[\begin{array}{c}
a_{1,1}x_1 + a_{1,2}x_2 + ...+a_{1,n}x_n\\
a_{2,1}x_1 + a_{2,2}x_2 + ...+a_{2,n}x_n\\
\vdots\\
a_{m,1}x_1 + a_{m,2}x_2 + ...+a_{m,n}x_n\\
\end{array} 
\right]
$

Notice that the right hand side is the dot product of the vector $x$ with a row in the array $\mathbf{A}$.

Lets create do this using lists of lists and loops in basic python.

In [8]:
# the matrix A is a 4 by 3 two dimensional array
A = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9],
     [10, 11, 12]]
x = [2, 4, 5]

#Lets compute the product and put the result in y
y = []
for row in range(len(A)):
    sum = 0
    for col in range(len(A[row])):
        sum += A[row][col] * x[col]
    y.append(sum)
print(y)
        

[25, 58, 91, 124]


The equivalent code using numpy is as follows.  You may have noticed that we use np.array to create both vectors and matrices.  This is because we can treat a vector as an array that only has one dimension.  

In [9]:
import numpy as np

# the matrix A is a 4 by 3 two dimensional array
A = np.array(
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9],
     [10, 11, 12]] )
x = np.array( 
    [2, 4, 5] )

#Lets compute the product and put the result in y
y = A.dot(x)

print(y)

# If you use the * operator,
# you will get pairwise computations and the result
# will be a matrix.

[ 25  58  91 124]


## Identity transformation
The matrix $\mathbf{A}$ is an identity matrix if $\mathbf{A}x = x$. (I.E. When you apply $\mathbf{A}$ to x, you get back x.)
For this to work, $\mathbf{A}$ must be a square matrix.

Here is the 4 by 4 identity matrix.
$\mathbf{A} = \left[\begin{array}{cccc}
1&0&0&0\\
0&1&0&0\\
0&0&1&0\\
0&0&0&1\\
\end{array} 
\right]
$

Lets see that it works in python using numpy!

In [29]:
import numpy as np

# the matrix A is a 4 by 4 identity matrix
A = np.array(
    [[1, 0, 0, 0], 
     [0, 1, 0, 0], 
     [0, 0, 1, 0],
     [0, 0, 0, 1]] )
x = np.array( 
    [2, 4, 5, -3] )

#Lets compute the product and put the result in y
y = A.dot(x)

print(y)

[ 2  4  5 -3]


# Combining a Matrix and a Matrix
The final thing that we will do is to multiply two matrices together to get another matrix. Suppose that $\mathbf{A}$ is an m by n matrix and $\mathbf{B}$ is an n by p matrix.  The result of multiplying $\mathbf{A}$ with $\mathbf{B}$ is a matrix $\mathbf{C}$ of size n by p.

standard operation is to multiply a matrix with a vector resulting in a new vector. This kind of operation is often linked with transformation of data.  Matrices used in this fashion are called _Transformation Matrices_.  We will define how to do the operation here and look at the corresponding python code and then show that it can be done faster with numpy.

$\mathbf{A}\mathbf{A} = 
\left[\begin{array}{cccc}
a_{1,1}&a_{1,2}&...&a_{1,n}\\
a_{2,1}&a_{2,2}&...&a_{2,n}\\
\vdots&\vdots&\ddots&\vdots\\
a_{m,1}&a_{m,2}&...&a_{m,n}
\end{array} 
\right]
\left[\begin{array}{ccccc}
b_{1,1}&b_{1,2}&...&b_{1,p}\\
b_{2,1}&b_{2,2}&...&b_{2,p}\\
b_{3,1}&b_{3,2}&...&b_{3,p}\\
\vdots&\vdots&\ddots&\vdots\\
b_{n,1}&b_{n,2}&...&b_{n,p}
\end{array} 
\right]
= 
\left[\begin{array}{ccccc}
c_{1,1}&c_{1,2}&...&c_{1,p}\\
c_{2,1}&c_{2,2}&...&c_{2,p}\\
c_{3,1}&c_{3,2}&...&c_{3,p}\\
\vdots&\vdots&\ddots&\vdots\\
c_{m,1}&c_{m,2}&...&c_{m,p}
\end{array} 
\right]
$

where
$c_{i,k} = a_{i,0}b_{0,k} + a_{i,1}b_{1,k} + ... + a_{i,n}b_{n,k}$ is just a dot product of row i from $\mathbf{A}$ with a column k from $\mathbf{B}$.  For this to work, the second dimension of $\mathbf{A}$ must match the first dimension of $\mathbf{B}$.


To code this in plain python we will need a triply nested loop.


In [33]:
# the matrix A is a 4 by 3 two dimensional array
A = [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9],
     [10, 11, 12]]

# the matrix b is a 3 by 5 two dimensional array
B = [[1, 2, 3, 7, 1], 
     [4, 5, 6, 9, 2], 
     [7, 8, 9, 4, 2]]

# Eventually, the result will be a 4 by 5 array
C = []


#Lets compute the product and put the result in y
for i in range(len(A)):
    # find row i
    row = []
    for k in range(len(B[0])):
        # Compute the value in location i,k
        sum = 0
        for j in range(len(A[i])):
            sum += A[i][j] * B[j][k]
        row.append(sum)
    # add the row now that we have it
    C.append(row)
print(C)

[[30, 36, 42, 37, 11], [66, 81, 96, 97, 26], [102, 126, 150, 157, 41], [138, 171, 204, 217, 56]]


and the numpy equivalent


In [35]:

import numpy as np

# the matrix A is a 4 by 3 two dimensional array
A = np.array(
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9],
     [10, 11, 12]])

# the matrix b is a 3 by 5 two dimensional array
B = np.array(
    [[1, 2, 3, 7, 1], 
     [4, 5, 6, 9, 2], 
     [7, 8, 9, 4, 2]])
    

# Eventually, the result will be a 4 by 5 array

C = A.dot(B)

print(C)

[[ 30  36  42  37  11]
 [ 66  81  96  97  26]
 [102 126 150 157  41]
 [138 171 204 217  56]]


### Take me to your leader (the official numpy docs)
http://www.numpy.org