# numpy

The main thing that we will use numpy for is vectors/arrays and the operations we can do on them.  The numpy library is written C, so it is fast, fast, fast.  If you are going to be using arrays in a computation task in python this is what you should use.  We will explore numpy a little bit and implement a few things ourselves, but mostly we will be using other packages that use numpy for their underlying operations.

## How do I use numpy?
You need to import the package.  In the olden days, the package name was np, so we are going to use that name when we work with numpy

In [1]:
import numpy as np

## Basic numpy structures
We will just work with vectors and matrices... or in numpy speak: arrays.  To create a numpy array we need to give it a list that contains the values in our array

## Vector
A vector is just a one-dimensional array. So to create it we just pass in a list with the values. Here are some examples...  S

In [3]:
#This vector has 3 values in it
vector1 = np.array([1, 2, 3])
print(vector1)

#This vector has 4 values in it
vector2 = np.array([1.5, 2.7, 8.9, 24])
print(vector2)

[1 2 3]
[ 1.5  2.7  8.9 24. ]


### Basic operations on Vectors

### Vector addition
If you have two vectors of the same size, you can add them together.  The resulting vector just adds the corresponding values together

In [12]:
#These vectors have 3 values in them
vectorA = np.array([1, 2, 3])
vectorB = np.array([0, 5, 10])

print(vectorA)
print(vectorB)
# Put the sum in vectorC
# Result is [1+0, 2+5, 3+10]
vectorC = vectorA + vectorB
print(vectorC)



[1 2 3]
[ 0  5 10]
[ 1  7 13]


### Vector products
When working with vectors we have a couple ways that we can do a
multiplication like operation.  The inner or dot product takes the
corresponding values in the two vectors and multiplies them together.
It then takes each of those products and adds them together resulting
in a single value.   The outer product is more complicated and used
less often. (It results in a 2D array.)

In [13]:
#The dot product of my two vectors
#Result is 1*0 + 2*5 + 3*10
product = vectorA @ vectorB
print(vectorA)
print(vectorB)
print(product)

# or we can do it as
product = vectorA.dot(vectorB)
print(product)

[1 2 3]
[ 0  5 10]
40
40


## Matrices
A matrix is a multidimensional array.  For our purposes, we will almost always work with 2D arrays, or sometimes 3D arrays.  To create an array we need to create a list of lists.  See the following example.

In [16]:
## The following is a 3 by 3 matrix
matrixA = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(matrixA)

## The following is a 2 by 4 matrix   (2 rows and 4 columns)
matrixB = np.array([[1, 2, 3, 4], 
                    [4, 5, 6, 8]])
print(matrixB)

# We can find the size of the array by asking for its shape
print(matrixA.shape)
print(matrixB.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [4 5 6 8]]
(3, 3)
(2, 4)


### Take me to your leader (the official docs)
http://www.numpy.org